// src/constants/auditActions.ts
export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  RECORD_CREATE: 'RECORD_CREATE',
  RECORD_UPDATE: 'RECORD_UPDATE',
  RECORD_DELETE: 'RECORD_DELETE',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
